# Generated by Django 4.1.7 on 2023-03-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guests_alter_menu_inventory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="ID",
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu",
            name="ID",
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
